changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - type:feat
    - title: Bug Fixes
      labels:
        - type:fix
    - title: Performance
      labels:
        - type:perf
    - title: Documentation
      labels:
        - type:docs
    - title: Other Changes
      labels:
        - "*"
  exclude:
    labels:
      - skip-changelog
      - dependencies
      - type:test
      - type:ci
      - type:build
      - type:chore
