name: Feature Request
description: Suggest an idea for fluxopt.
labels: [type:feat]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for letting us know about your idea!
  - type: textarea
    id: description
    attributes:
      label: What can be improved?
      placeholder: Tell us what you would like to see!
      value: "fluxopt should model ..."
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of fluxopt are you using?
      placeholder: v0.0.1
    validations:
      required: true
